import { OrderCategory } from '@/types/order';

export const menuItemsSeed = [
  { id: '1', name: 'Χωριάτικη Σαλάτα', category: 'Κρύα' as OrderCategory },
  { id: '2', name: 'Πράσινη Σαλάτα', category: 'Κρύα' as OrderCategory },
  { id: '3', name: 'Ρόκα με Παρμεζάνα', category: 'Κρύα' as OrderCategory },
  { id: '4', name: 'Καίσαρ', category: 'Κρύα' as OrderCategory },
  { id: '5', name: 'Ντοματοσαλάτα', category: 'Κρύα' as OrderCategory },
  { id: '6', name: 'Ζεστή Σαλάτα με Κοτόπουλο', category: 'Ζεστές' as OrderCategory },
  { id: '7', name: 'Σαλάτα με Γαρίδες', category: 'Ζεστές' as OrderCategory },
  { id: '8', name: 'Μπριζόλα Χοιρινή', category: 'Ψησταριά' as OrderCategory },
  { id: '9', name: 'Μπριζόλα Μοσχαρίσια', category: 'Ψησταριά' as OrderCategory },
  { id: '10', name: 'Κοτόπουλο Φιλέτο', category: 'Ψησταριά' as OrderCategory },
  { id: '11', name: 'Μπιφτέκι', category: 'Ψησταριά' as OrderCategory },
  { id: '12', name: 'Σουβλάκι Χοιρινό', category: 'Ψησταριά' as OrderCategory },
  { id: '13', name: 'Σουβλάκι Κοτόπουλο', category: 'Ψησταριά' as OrderCategory },
  { id: '14', name: 'Μουσακάς', category: 'Μαγειρευτό' as OrderCategory },
  { id: '15', name: 'Παστίτσιο', category: 'Μαγειρευτό' as OrderCategory },
  { id: '16', name: 'Παπουτσάκια', category: 'Μαγειρευτό' as OrderCategory },
  { id: '17', name: 'Γιουβέτσι', category: 'Μαγειρευτό' as OrderCategory },
  { id: '18', name: 'Κοκκινιστό', category: 'Μαγειρευτό' as OrderCategory },
  { id: '19', name: 'Κόκα Κόλα', category: 'Ποτά' as OrderCategory },
  { id: '20', name: 'Σπράιτ', category: 'Ποτά' as OrderCategory },
  { id: '21', name: 'Φάντα', category: 'Ποτά' as OrderCategory },
  { id: '22', name: 'Νερό', category: 'Ποτά' as OrderCategory },
  { id: '23', name: 'Μπύρα', category: 'Ποτά' as OrderCategory },
  { id: '24', name: 'Κρασί Λευκό', category: 'Ποτά' as OrderCategory },
  { id: '25', name: 'Κρασί Κόκκινο', category: 'Ποτά' as OrderCategory },
  { id: '26', name: 'Καφές', category: 'Ποτά' as OrderCategory },
];